spring.application.name=course-log

spring.datasource.url=jdbc:mysql://d6vscs19jtah8iwb.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/a4b3d3mdq0sglt5r?serverTimezone=UTC
spring.datasource.username=ho85i4im04n6pfks
spring.datasource.password=y9em799uh38fqsbo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=5

logging.level.com.joelhorstman.cst323.courselog=INFO
server.port=8080